ALTER TABLE sonora_natalidad
DROP COLUMN hora_nac,
DROP COLUMN minuto_nac,
DROP COLUMN comparecio,
DROP COLUMN dis_re_oax,
DROP COLUMN pos_mad,
DROP COLUMN pos_pad,
DROP COLUMN lugar_part,
DROP COLUMN q_atendio,
DROP COLUMN hijos_vivo,
DROP COLUMN hijos_sobr,
DROP COLUMN edociv_mad,
DROP COLUMN dia_reg,
DROP COLUMN dia_nac;